<script>
const TANZANIA_REGIONS = {
  "Arusha": ["Arusha Mjini", "Arusha Vijijini", "Karatu", "Longido", "Monduli", "Ngorongoro font", "Meru"],
  "Dar es Salaam": ["Ilala", "Kinondoni", "Temeke", "Kigamboni", "Ubungo"],
  "Dodoma": ["Dodoma Mjini", "Bahi", "Chamwino", "Chemba", "Kondoa", "Kongwa", "Mpwapwa"],
  "Geita": ["Geita Mjini", "Bukombe", "Chato", "Mbogwe", "Nyang'hwale"],
  "Iringa": ["Iringa Mjini", "Iringa Vijijini", "Kilolo", "Mufindi"],
  "Kagera": ["Bukoba Mjini", "Bukoba Vijijini", "Biharamulo", "Karagwe", "Kyerwa", "Misenyi", "Muleba", "Ngara"],
  "Katavi": ["Mpanda Mjini", "Mpanda Vijijini", "Mlele"],
  "Kigoma": ["Kigoma Ujiji", "Kigoma Vijijini", "Buhigwe", "Kakonko", "Kasulu Mjini", "Kasulu Vijijini", "Kibondo", "Uvinza"],
  "Kilimanjaro": ["Moshi Mjini", "Moshi Vijijini", "Hai", "Siha", "Rombo", "Mwanga", "Same"],
  "Lindi": ["Lindi Mjini", "Lindi Vijijini", "Kilwa", "Liwale", "Nachingwea", "Ruangwa"],
  "Manyara": ["Babati Mjini", "Babati Vijijini", "Hanang", "Kiteto", "Mbulu", "Simanjiro"],
  "Mara": ["Musoma Mjini", "Musoma Vijijini", "Bunda", "Butiama", "Rorya", "Serengeti", "Tarime"],
  "Mbeya": ["Mbeya Mjini", "Mbeya Vijijini", "Chunya", "Kyela", "Mbarali", "Rungwe"],
  "Morogoro": ["Morogoro Mjini", "Morogoro Vijijini", "Gairo", "Kilombero", "Kilosa", "Mvomero", "Ulanga", "Malinyi"],
  "Mtwara": ["Mtwara Mjini", "Mtwara Vijijini", "Masasi Mjini", "Masasi Vijijini", "Nanyumbu", "Newala", "Tandahimba"],
  "Mwanza": ["Nyamagana", "Ilemela", "Kwimba", "Magu", "Misungwi", "Sengerema", "Ukerewe"],
  "Njombe": ["Njombe Mjini", "Njombe Vijijini", "Makambako Mjini", "Makete", "Ludewa font", "Wanging'ombe"],
  "Pwani": ["Kibaha Mjini", "Kibaha Vijijini", "Bagamoyo", "Kisarawe", "Mafia", "Mkuranga", "Rufiji"],
  "Rukwa": ["Sumbawanga Mjini", "Sumbawanga Vijijini", "Kalambo", "Nkasi"],
  "Ruvuma": ["Songea Mjini", "Songea Vijijini", "Mbinga Mjini", "Mbinga Vijijini", "Namtumbo", "Nyasa", "Tunduru"],
  "Shinyanga": ["Shinyanga Mjini", "Shinyanga Vijijini", "Kahama Mjini", "Kishapu", "Msalala"],
  "Simiyu": ["Bariadi Mjini", "Bariadi Vijijini", "Busega", "Itilima", "Maswa", "Meatu"],
  "Singida": ["Singida Mjini", "Singida Vijijini", "Ikungi", "Iramba", "Manyoni", "Mkalama"],
  "Songwe": ["Vwawa", "Ileje", "Mbozi", "Momba"],
  "Tabora": ["Tabora Mjini", "Igunga", "Kaliua", "Nzega", "Sikonge", "Urambo", "Uyui"],
  "Tanga": ["Tanga Mjini", "Handeni Mjini", "Handeni Vijijini", "Kilindi", "Korogwe Mjini", "Korogwe Vijijini", "Lushoto", "Mkinga", "Muheza", "Pangani"],
  "Unguja Kaskazini": ["Kaskazini A", "Kaskazini B"],
  "Unguja Kusini": ["Kati", "Kusini"],
  "Mjini Magharibi": ["Mjini", "Magharibi"],
  "Pemba Kaskazini": ["Wete", "Micheweni"],
  "Pemba Kusini": ["Chake Chake", "Mkoani"]
};
</script>
